"Yaml Config File for Traffic Sign Detection Training"

path: trafficSigns  # dataset root dir
train: train.txt  # train images 
val: val.txt  # val images 
test: test.txt  # test images

# Classes
names:
  0: highway_end
  1: highway
  2: no_entry
  3: one_way
  4: parking
  5: crossing
  6: priority
  7: roundabout
  8: stop