[package]
name = "rs_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", default-features = false, features = ["thread-pool", "linux-theme-detection", "tiny-skia", "x11", "image"] }
rs_ipc = { path = "../rs_ipc", default-features = false }