models_dir_path: 'objects\models\'
pipeline_config_path: 'objects\config\parallel_pipeline_config.json'
roi_config_path: 'objects\config\roi.json'
video_name: 'Realsense'
videos_dir: 'videos'
results_dir: 'results'