models_dir_path: 'objects/models/'
videos_dir: 'videos'
recordings_dir: 'videos/recordings'
pipeline_config_path: 'objects/config/lane_detect_config.json'
roi_config_path: 'objects/config/roi.json'
video_name: 'qualifiers_2.mp4'
visualize_only_final: True
save_video: True
fps: 30
width: 1920
height: 1080